name: Docker Image

on:
  push:
    branches: [ fun ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker build --label org.opencontainers.image.revision=${{github.sha}} --iidfile id .
        docker tag    "$(cat id)" "ghcr.io/${{github.repository}}:latest"
   - name: Push
     run: |
        docker login  "ghcr.io" -u ${{github.repository_owner}} --password-stdin <<<"${{secrets.GHCR_TOKEN}}"
        docker push   "ghcr.io/${{github.repository}}:latest"
        docker logout "ghcr.io"
